### ISSUE TITLE
[feature] the basic framework of capstan TODOs

### ISSUE THREAD

**Issue by mozhuli** [ZJU-SEL/capstan#2]
Testing workload：

- [x] [P0] Basic workflow of capstan  #3 @mozhuli
- [x] [P0] The interface of workload  #3 #6 @mozhuli
- [x] [P0] The interface of testing tool  #3 #6 @mozhuli

Collect data:

- [x] [P1] Basic workflow of data collecting   #11 @mozhuli
- [x] [P1] The interface of data collecting   #11 @mozhuli

Dashboard(grafana):

- [ ] [P1] Design a generic template of dashboard

/cc @ZJU-SEL/capstan-dev
